- name: Copy MongoDB Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb server
  ansible.builtin.yum:
    name: mongodb-org
    state: latest

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable nginx
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes