- name: load golang
  ansible.builtin.import_role:
    name: common
    tasks_from: golang

- name: Load Prometheus Node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter